node {
   def mvnHome
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      git 'https://github.com/npraveenk1/game-of-life.git'
      // Get the Maven tool.
      // ** NOTE: This 'M3' Maven tool must be configured
      // **       in the global configuration.           
      mvnHome = tool 'MVN339'
   }
   stage('Build') {
      // Run the maven build
      if (isUnix()) {
         sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
      } else {
         bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
      }
   }
   stage('Junit') {
      junit '**/target/surefire-reports/*.xml'
   }
   stage('Results') {
      junit '**/target/surefire-reports/TEST-*.xml'
      archive 'gameoflife-core/target/*.jar,gameoflife-web/target/*.war'
   }
}
